### ISSUE TITLE
Since addition of Finish Off code Mind Sear is used also on single targets with AoE toggle on

### ISSUE THREAD

**Issue by LiquidAtoR** [Yobleed/NerdPack-Yobleed#10]
Since the introduction of your Finish Off code (as far as I tested the versions) Mind Sear is used on single targets when using the AoE toggle.
Before it wasn't using Mind Sear in single target situations (and it shouldn't I think).
Running the latest version and the last one from the 26th December I believe is where the Mind Sear/Mind Flay difference is with AoE toggled on, on single targets.

**Comment by Yobleed** [comment]
@LiquidAtoR 
{'Mind Sear', '{spell(Mind Blast).cooldown > 0 & !talent(Mind Spike) & toggle(AOE) & !advanced} || {spell(Mind Blast).cooldown > 0 & !talent(Mind Spike) & target.area(10).enemies >= 3 & toggle(AOE) & advanced}','target'}, 

It will be used if AOE is toggled on and if ur using a Generic Unlocker (like Olua).

**Comment by LiquidAtoR** [comment]
I'm using oLua indeed.
Just found it strange it didn't do that before the finish code was added.
If it's intended as per your formula just ignore my comment 👍

**Comment by Yobleed** [comment]
@LiquidAtoR Generic cant detect stacked enemies. Only stacked enemies on Player
