### ISSUE TITLE
version f467ac8 no DPS in 5 man dungeons until Treasure Goblin

### ISSUE THREAD

**Issue by LiquidAtoR** [Yobleed/NerdPack-Yobleed#11]
I just ran a 5 man dungeon (Halls of Valor) and it didn't do any DPS for atonement healing whatsoever.
It only dished out atonements (I had OOC Atonements on) pleas, shadowmend and shields. Nothing else.
Until the very end where the treasure goblin appeared, there it did do DPS...

Following options set:
OOC Atonements On
Solo Rotation Off
Master Toggle On
Spike Damage On
Interrupts Off
Multitarget On
OOC Healing On
Dispell On
Cooldowns On

All 3 hotkeys enabled (PW: Barrier, MD and Pause), Body and Soul for movement.
And I think rest is pretty much at the default settings.

Talents 1/3 - 2/2 - 3/1 - 4/3 - 5/2 - 6/3 - 7/1

**Comment by LiquidAtoR** [comment]
nvm, solo has to be on, maybe consider renaming that :P

**Comment by LiquidAtoR** [comment]
On a sidenote with oLua you will have to reload every time you enter a dungeon (or come out of one) for the rotation to resume it's work.

**Comment by Yobleed** [comment]
I'm working on Spike Damage and the reload can't be fixed for some reason...

**Comment by Yobleed** [comment]
Spike Damage should only be toggled if you expect spike damage inc. Don't use on a normal situation

**Comment by LiquidAtoR** [comment]
So the reload thing is not related to oLua (e.g. a paid unlocker has the same issue?)
Yeah, I figured that much with the toggle thingy :)
Thanks for all the work you put in there, the CR is really shaping up.

**Comment by LiquidAtoR** [comment]
That the CR stops also seems to happen when zoning in dungeons (like HoV) and I also had it happen it stopped when someone used that Piccolo of the Flaming Fire (that dance trinket/toy) and it made me dance. Just a FYI.

**Comment by Yobleed** [comment]
wierd shit man
