### ISSUE TITLE
Does not work(

### ISSUE THREAD

**Issue by PapkaZol** [Yobleed/NerdPack-Yobleed#13]
After killing the mobs pair stops working. And the issue here is such a mistake. How can I fix it? Previously everything worked perfectly.

3x NerdPack\conditions\talents-Таланты.lua:33: Usage: GetTalentInfoByID(talentID, specGroupIndex [, isInspect, inspectUnit])
[C]: ?
NerdPack\conditions\talents-Таланты.lua:33: in function <NerdPack\conditions\talents.lua:32>
(tail call): ?
(tail call): ?
NerdPack\system\dsl.lua:45: in function <NerdPack\system\dsl.lua:45>
(tail call): ?
NerdPack\system\dsl.lua:61: in function <NerdPack\system\dsl.lua:56>
(tail call): ?
NerdPack\system\dsl.lua:92: in function <NerdPack\system\dsl.lua:90>
(tail call): ?
NerdPack\system\parser.lua:98: in function `Parse'
NerdPack\system\parser.lua:89: in function `Parse'
NerdPack\system\parser.lua:127: in function <NerdPack\system\parser.lua:120>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:

**Comment by PapkaZol** [comment]
This error pops up after switching to another target. As it is still possible to fix it?

**Comment by Yobleed** [comment]
what cr are you using?

**Comment by PapkaZol** [comment]
CR? Combat Ress? What is the cr?

**Comment by PapkaZol** [comment]
This error appears in the Shadow spec. Others I have not tried. Previously, such an error does not occur.

**Comment by PapkaZol** [comment]
Discipline Priest works fine. But Shadow Priest gives an error after the change of purpose (

**Comment by Yobleed** [comment]
I changed Talent names to ID's can u try shadow pls?

**Comment by PapkaZol** [comment]
Everything was working perfectly. Thank you so much for change!
