### ISSUE TITLE
Interrupt Cast void torrent

### ISSUE THREAD

**Issue by br4bit** [Yobleed/NerdPack-Yobleed#15]
Hi, there's a small issue on shadow rotation when enter in voidform with burst activate. 
Void torrent stop channeling cast because of power infusion cast...

sorry for english

ty :P

**Comment by Yobleed** [comment]
Ill look into it

**Comment by Yobleed** [comment]
What NeP version are you running? It shouldnt be doing that if I read the code

**Comment by br4bit** [comment]
I use 1.8 version. When i activate cooldowns and go in voidform it will cast together Void Torrent and Power Infusione and break the channeling of void torrent.
I saw other thing, sometimes mindflay not cast, do you think it's oLUA unlocker?

**Comment by Yobleed** [comment]
seems like a broken NeP version to me. Join discord and so the developer can look into the issue https://discord.gg/Z49quJ

**Comment by MrTheSoulz** [comment]
Dosent seem like a nep issue, just bad cr logic.
when you use !spell you should make sure you dont interrupt other important spells.
if this is not the case, open a bug report on nep's issues.

**Comment by Yobleed** [comment]
```	--Mind Flay if Mind Blast is on cooldown
	{'Mind Flay', nil,'target'},```

It should be casting Mind Flay. 

Anyway I'll add an extra Mind Flay line 
Update for now and lemme know what it does

**Comment by br4bit** [comment]
Ok ty you're the best :)
