### ISSUE TITLE
heal pets

### ISSUE THREAD

**Issue by PapkaZol** [Yobleed/NerdPack-Yobleed#8]
The rotation Discipline Priest used treatment hunter pets, use Power Word: Shield.. How to turn this off?

**Comment by Yobleed** [comment]
so it shields the pet?... I'll test it

**Comment by PapkaZol** [comment]
Yes. Bestows the animal hunter Power Word: Shield and Plea.  Perhaps it is from the fact that they have not turned off aggro.

**Comment by Yobleed** [comment]
seems like pets are targeted in Lowest roster not sure how to avoid it at the moment. Will take a look into it
